"""Structural guards for the two PR #189 owner review comments (R10 / Group G2, round 2) plus a
mid-round addition of the SAME error class - fixing the CLASS, not just the reported lines:

1. `discussion_r3701240313` (agents/odoo-installable-prober.md:131) - the Odoo manifest file is
   `__manifest__.py`; the merge_log_line EXAMPLE said bare `manifest.py`. An agent following a
   wrong filename goes looking for a file that does not exist under that name in any Odoo module.
   This test sweeps for the GENERAL class: any bare `manifest.py` / `init.py` (missing the real
   file's double underscores) anywhere in agent-facing prose, in EITHER plugin.

2. `discussion_r3701288606` (skills/odoo-i18n/SKILL.md:134) - P0 tier 5 hardcoded a `["vi_VN"]`
   default target-translation-language. A public, multi-tenant plugin must never assume a locale
   nobody asked for. This test sweeps for the GENERAL class: any hardcoded locale/language DEFAULT
   (not merely a locale appearing in an EXAMPLE) in agent-facing prose, in EITHER plugin.

3. Mid-round addition - a bare `coding_guidelines/<version>/INDEX.md` path (missing its
   `skills/_shared/` root) is not resolvable by a runtime agent the way every other correctly-
   written occurrence of the identical instruction is. This test sweeps for the GENERAL class two
   ways: (a) a narrow structural check that any `coding_guidelines/` reference OUTSIDE its own
   directory carries the `skills/_shared/` root, and (b) a GENERAL existence check that every
   `${CLAUDE_PLUGIN_ROOT}/...` path referenced anywhere (with `<placeholder>` segments wildcarded)
   resolves to at least one real file/dir on disk, in EITHER plugin.

Design notes (why each check is a STRUCTURAL exemption, never a file allowlist):

- Whole-tree `rglob("*.md")` across every plugin under `plugins/`, whitespace not required to
  differ (single-line matching keeps line:col precision), generated
  `<!-- BEGIN/END GENERATED TOOLS -->` regions blanked first (that block is regenerated by
  `make gen` from a separate SSOT and is out of scope for hand-authored prose defects).
- Check 1 exempts a line that also names a recognized RUNTIME-ARTIFACT-PATH marker
  (`ISOLATE_DIR` / `SHARE_DIR`) - such a line is describing a plugin-chosen CACHE/DUMP filename
  under the run's scratch directory, not making a claim about Odoo's own module layout (verified
  case: `skills/odoo-forward-port/**`'s `<ISOLATE_DIR>/forward-port/<slug>/installable/<module>/
  manifest.py` dump path, which correctly reads the real `__manifest__.py` as its SOURCE and only
  chooses an arbitrary LOCAL destination name - a different fact from Comment 1's defect). This is
  a structural marker (a recognized path-prefix convention used repo-wide), not a per-file
  allowlist - it would exempt ANY future site that uses the same convention, and catches a future
  site that does NOT.
- Check 2 exempts a line where the locale code is CLEARLY illustrative: preceded on the same line
  by an explicit example marker (`e.g.`, `example`) BEFORE the locale code, or matching the
  `<locale>`-suffixed filename-pattern idiom (`NN-slug.<locale>.ext`, `index_<locale>.html`, a
  literal filename with a `.xx_YY.` infix). What is NEVER exempted: a locale code co-occurring with
  the word `default` or `fallback` on the same line, describing an assignment/tier resolution
  outcome rather than a naming pattern - that co-occurrence is exactly what both confirmed defects
  looked like, and is inherently rare in legitimate example prose (verified: zero false positives
  across the whole tree once the two real defects were fixed).
- Check 3a (general existence) treats `${CLAUDE_PLUGIN_ROOT}` as the plugin root that OWNS the
  referencing file (a path in an `odoo-ai-agents` file resolves against
  `plugins/odoo-ai-agents/`), replaces any `<placeholder>` path segment with a glob wildcard
  (there is no way to check a literal `<version>` segment against disk - it is a template, not a
  real path - so it is generalised to "does ANY concrete substitution exist"), and requires at
  least one match. Check 3b (bare `coding_guidelines/`) is scoped to occurrences OUTSIDE
  `skills/_shared/coding_guidelines/` itself - a file living IN that directory may legitimately
  reference a SIBLING file by a same-directory-relative bare name (e.g. the top-level
  `coding_guidelines/INDEX.md` pointing at `<version>/INDEX.md`); a file living ANYWHERE ELSE in
  the plugin has no such relative relationship and needs the qualified root.

Known cross-group exception (tracked, not suppressed): `skills/odoo-coding/SKILL.md` carries one
remaining bare `coding_guidelines/<version>/INDEX.md` reference. That file is owned by a
concurrently-active group (not this test's author) and the exact fix has been handed off
(`/tmp/odoo-mcp-client-research/phase2/46-handoff-G2.md` item 4) rather than edited directly, per
this round's one-writer-per-file rule. This test does NOT allowlist that file - it will correctly
report the failure until the owning group applies the handed-off fix, at which point it goes green
with no change to this test.
"""
from __future__ import annotations

import glob
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLUGINS_DIR = ROOT / "plugins"
PLUGIN_NAMES = ("odoo-ai-agents", "odoo-semantic-mcp", "git-toolkit")

_GENERATED_BLOCK = re.compile(
    r"<!-- BEGIN GENERATED TOOLS -->.*?<!-- END GENERATED TOOLS -->", re.S
)


def _plugin_roots():
    for name in PLUGIN_NAMES:
        p = PLUGINS_DIR / name
        if p.is_dir():
            yield name, p


def _iter_md_files():
    for _name, plugin_dir in _plugin_roots():
        for path in sorted(plugin_dir.rglob("*.md")):
            yield path


def _blanked_lines(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    text = _GENERATED_BLOCK.sub("", text)
    return text.splitlines()


def _rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


# ---------------------------------------------------------------------------
# 1. Bare Odoo dunder-filename: `manifest.py` / `init.py` missing `__`
# ---------------------------------------------------------------------------

_BARE_MANIFEST_RE = re.compile(r"(?<!_)\bmanifest\.py\b")
_BARE_INIT_RE = re.compile(r"(?<!_)\binit\.py\b")

# A line naming a recognized runtime-artifact-path marker describes a
# plugin-chosen cache/dump location under the run's scratch dir, never a
# claim about Odoo's own module layout.
_ARTIFACT_MARKERS = ("ISOLATE_DIR", "SHARE_DIR")


def _bare_filename_hits(pattern: re.Pattern) -> list[str]:
    hits = []
    for path in _iter_md_files():
        for lineno, line in enumerate(_blanked_lines(path), start=1):
            if not pattern.search(line):
                continue
            if any(marker in line for marker in _ARTIFACT_MARKERS):
                continue
            hits.append(f"{_rel(path)}:{lineno}: {line.strip()}")
    return hits


def test_no_bare_manifest_py_filename():
    hits = _bare_filename_hits(_BARE_MANIFEST_RE)
    assert not hits, (
        "Bare 'manifest.py' found in agent-facing prose - the real Odoo file is "
        "'__manifest__.py'; an agent following this looks for a file that does not exist:\n"
        + "\n".join(hits)
    )


def test_no_bare_init_py_filename():
    hits = _bare_filename_hits(_BARE_INIT_RE)
    assert not hits, (
        "Bare 'init.py' found in agent-facing prose - the real Odoo file is '__init__.py':\n"
        + "\n".join(hits)
    )


# ---------------------------------------------------------------------------
# 2. Hardcoded locale/currency DEFAULT (vs. a locale used only as an EXAMPLE)
# ---------------------------------------------------------------------------

_LOCALE_RE = re.compile(r"\b[a-z]{2}_[A-Z]{2}\b")
# `\w*` (not a trailing `\b`) so this also matches the JSON-key continuation
# `default_languages` (the actual i18n.json registry field) as well as
# `defaults`/`defaulting`, not just the bare word `default`.
_DEFAULT_WORD_RE = re.compile(r"\b(default|fallback)\w*", re.IGNORECASE)

# Structural EXAMPLE markers that, appearing before the locale code on the
# same line, mean the locale is illustrating a NAMING PATTERN or a plain
# example list, not an assignment/resolution outcome.
_EXAMPLE_MARKER_RE = re.compile(r"\b(e\.g\.|example)\b", re.IGNORECASE)
# The `<locale>`-suffixed filename idiom (`index_<locale>.html`,
# `NN-slug.<locale>.ext`, a literal `.xx_YY.` infix) is a format
# illustration, not a default assignment.
_LOCALE_FILENAME_IDIOM_RE = re.compile(r"<locale>|\.\w+_[A-Z]{2}\.\w")

# A genuine default ASSIGNMENT names the value right next to the word
# ("Default `[\"vi_VN\"]`", "(default vi_VN)", "the default ... is `vi_VN`",
# "Fallback [\"vi_VN\"]", `{"default_languages":["vi_VN"]}`) - every confirmed
# defect had the locale code within a few words of "default"/"fallback". A
# long compound sentence that separately mentions "default" for an unrelated
# field (`demo (bool, default false)`) and, much later, a locale code for a
# DIFFERENT reason (the `en_US` HARD RULE) is not the same claim - bounded by
# a character window so the two only count together when they are plausibly
# about THE SAME value.
_PROXIMITY_WINDOW = 25


def _locale_default_hits() -> list[str]:
    hits = []
    for path in _iter_md_files():
        for lineno, line in enumerate(_blanked_lines(path), start=1):
            for default_match in _DEFAULT_WORD_RE.finditer(line):
                window_start = max(0, default_match.start() - _PROXIMITY_WINDOW)
                window_end = default_match.end() + _PROXIMITY_WINDOW
                window = line[window_start:window_end]
                locale_match = _LOCALE_RE.search(window)
                if not locale_match:
                    continue
                # Example / naming-pattern illustration BEFORE the code -> exempt.
                example_marker = _EXAMPLE_MARKER_RE.search(window)
                if example_marker and example_marker.start() < locale_match.start():
                    continue
                if _LOCALE_FILENAME_IDIOM_RE.search(window):
                    continue
                hits.append(f"{_rel(path)}:{lineno}: {line.strip()}")
                break
    return hits


def test_no_hardcoded_locale_default():
    hits = _locale_default_hits()
    assert not hits, (
        "A locale code co-occurs with 'default'/'fallback' (within a "
        f"{_PROXIMITY_WINDOW}-char window) in agent-facing prose - this repo is public and "
        "multi-tenant; the target language must be a resolved or explicitly-requested input, "
        "never a hardcoded default a user did not ask for:\n" + "\n".join(hits)
    )


# Hardcoded currency is the same defect CLASS in principle (see the
# docstring's "plus hardcoded currency" instruction) but is NOT automated
# here: a whole-tree sweep for a currency code co-occurring with
# "default"/"fallback" found exactly one candidate
# (`skills/odoo-doc-illustration/references/app-store-template.md` - the
# manifest `currency` key table row: "`EUR` (default) or `USD` only"), and it
# is judged NOT a defect - it documents the Odoo APP STORE'S OWN accepted
# currency values for a paid listing (an external platform constraint, like
# `en_US` being Odoo's own base language), not a value this plugin defaults
# on the user's behalf. One example is not enough to build a reliable
# structural rule that tells "documents an external platform's fixed
# requirement" apart from "hardcodes an arbitrary default" without
# overfitting to that single row, so this stays a manually-reviewed finding
# (recorded in the round's report) rather than an automated assertion.


# ---------------------------------------------------------------------------
# 3. In-repo path references that do not resolve as written
# ---------------------------------------------------------------------------

# 3a. General check: every `${CLAUDE_PLUGIN_ROOT}/...` backtick-quoted path,
# with any `<placeholder>` segment wildcarded, must resolve to >=1 real
# file/dir under the OWNING plugin's root.
_CLAUDE_PLUGIN_PATH_RE = re.compile(r"`\$\{CLAUDE_PLUGIN_ROOT\}/([^`]+)`")
_PLACEHOLDER_SEGMENT_RE = re.compile(r"<[^/>]+>")


def _general_path_hits() -> list[str]:
    hits = []
    for name, plugin_dir in _plugin_roots():
        for path in sorted(plugin_dir.rglob("*.md")):
            for lineno, line in enumerate(_blanked_lines(path), start=1):
                for m in _CLAUDE_PLUGIN_PATH_RE.finditer(line):
                    raw = m.group(1)
                    # Strip a trailing prose continuation: a `§ Section`
                    # pointer, or a `:<line>` locator, both of which are
                    # valid prose AFTER the real path ends.
                    cut = re.split(r"[\s§]", raw, maxsplit=1)[0]
                    cut = cut.rstrip(").,:;").split(":")[0] if cut.count(":") else cut.rstrip(").,:;")
                    globpath = _PLACEHOLDER_SEGMENT_RE.sub("*", cut)
                    candidate = str(plugin_dir / globpath)
                    if not glob.glob(candidate):
                        hits.append(f"{_rel(path)}:{lineno}: ${{CLAUDE_PLUGIN_ROOT}}/{cut}")
    return hits


def test_claude_plugin_root_paths_resolve():
    hits = _general_path_hits()
    assert not hits, (
        "A `${CLAUDE_PLUGIN_ROOT}/...` path reference does not resolve to any real file/dir "
        "under its owning plugin (placeholder segments wildcarded) - a runtime agent following "
        "it gets nothing:\n" + "\n".join(hits)
    )


# 3b. Narrow structural check: `coding_guidelines/` referenced OUTSIDE its
# own directory must carry the `skills/_shared/` root (with or without the
# `${CLAUDE_PLUGIN_ROOT}/` prefix) - a bare reference from a file that is NOT
# co-located with `coding_guidelines/` cannot resolve relative to anything.
# Scoped to backtick-delimited spans only: a LITERAL path reference an agent
# is meant to open is always backtick-quoted throughout this repo (`open
# \`coding_guidelines/<version>/INDEX.md\` first`); a bare-prose MENTION of
# the concept by name with no backticks (e.g. "use the coding_guidelines/14.0
# fallback for a different fact") is describing a mechanism, not handing the
# agent something to resolve - that is a real, repo-wide convention
# difference, not a per-file exception.
_BACKTICK_SPAN_RE = re.compile(r"`([^`]*)`")
_CODING_GUIDELINES_TOKEN_RE = re.compile(r"coding_guidelines/")
_QUALIFIED_ROOT = "skills/_shared/"
_OWN_DIR_PREFIXES = tuple(
    f"plugins/{name}/skills/_shared/coding_guidelines/" for name, _ in _plugin_roots()
)


def _bare_coding_guidelines_hits() -> list[str]:
    hits = []
    for path in _iter_md_files():
        rel = _rel(path)
        if rel.startswith(_OWN_DIR_PREFIXES):
            # A file living inside coding_guidelines/ may legitimately use a
            # same-directory-relative bare reference to a sibling file.
            continue
        for lineno, line in enumerate(_blanked_lines(path), start=1):
            for span in _BACKTICK_SPAN_RE.finditer(line):
                content = span.group(1)
                for m in _CODING_GUIDELINES_TOKEN_RE.finditer(content):
                    preceding = content[: m.start()]
                    if preceding.endswith(_QUALIFIED_ROOT):
                        continue
                    hits.append(f"{rel}:{lineno}: {line.strip()}")
    return hits


def test_coding_guidelines_reference_is_qualified():
    hits = _bare_coding_guidelines_hits()
    assert not hits, (
        "A bare 'coding_guidelines/' reference (missing the 'skills/_shared/' root) was found "
        "outside the coding_guidelines/ directory itself - not resolvable relative to the "
        "referencing file. Known pending item: skills/odoo-coding/SKILL.md is owned by a "
        "concurrently-active group; the exact fix is in "
        "/tmp/odoo-mcp-client-research/phase2/46-handoff-G2.md item 4.\n" + "\n".join(hits)
    )
